apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  namespace: staging
  labels:
    app: baz
    deployment: baz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baz
      deployment: baz
  template:
    metadata:
      labels:
        app: baz
        deployment: baz
    spec:
      containers:
        - name: baz
          image: baz:stage-v1.2.3-rc1
          env:
            - name: BAZ_FEATURE_FLAG
              value: enabled
            - name: BAZ_API_VERSION
              value: v2
          envFrom: []
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug
              containerPort: 5005
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/myapp/data
              readOnly: false
            - name: config
              mountPath: /etc/myapp/config
              readOnly: true
            - name: cache
              mountPath: /var/cache/myapp
              readOnly: false
            - name: projected-secrets
              mountPath: /var/secrets
              readOnly: true
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baz-data
        - name: config
          configMap:
            name: baz-config
        - name: cache
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: projected-secrets
          projected:
            defaultMode: 256
            sources:
              - secret:
                  name: baz-secrets
                  items:
                    - key: db-user
                      path: database/username
                    - key: db-password
                      path: database/password
              - configMap:
                  name: baz-config
                  items:
                    - key: redis-url
                      path: config/redis-url
              - configMap:
                  name: stage-cluster-ca
                  items:
                    - key: ca.crt
                      path: config/cluster-ca.crt
              - downwardAPI:
                  items:
                    - path: pod/name
                      fieldRef:
                        fieldPath: metadata.name
                    - path: pod/namespace
                      fieldRef:
                        fieldPath: metadata.namespace
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: baz
---
apiVersion: v1
kind: Service
metadata:
  name: baz
  namespace: staging
  labels:
    app: baz
    deployment: baz
spec:
  type: ClusterIP
  selector:
    app: baz
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: baz-debug
  namespace: staging
  labels:
    app: baz
    deployment: baz
  annotations:
    description: Debug service for remote debugging
spec:
  type: ClusterIP
  selector:
    app: baz
    component: backend
  ports:
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
  sessionAffinity: None
